### ISSUE TITLE
Build out entire dashboard page

### ISSUE THREAD

**Issue by kidcalebjacob** [gideonchrapko/tune-tube-app#6]

**Comment by kidcalebjacob** [comment]
Ready for review

**Comment by gideonchrapko** [comment]
A popular routing trend you'll see is using nested routes and we should use it for routes on the dashboard page.

When you click creator analytics, sounds, sync etc it should take you to be taken to a nested route at localhost:3000/dashboard/creator-analytics, localhost:3000/dashboard/sounds, localhost:3000/dashboard/sync etc.

you can see the documentation on how to set it up here https://nextjs.org/docs/app/building-your-application/routing#nested-routes but you can also ask chat gpt how to set that up
